import turtle

miTortugaMaria = turtle.Turtle()
miTortugaMaria.forward(50)
miTortugaMaria.left(45)
miTortugaMaria.forward(50)
miTortugaMaria.left(45)
miTortugaMaria.forward(50)
miTortugaMaria.left(45)
miTortugaMaria.forward(50)
miTortugaMaria.left(45)
miTortugaMaria.forward(50)
miTortugaMaria.left(45)
miTortugaMaria.forward(50)
miTortugaMaria.left(45)
miTortugaMaria.forward(50)
miTortugaMaria.left(45)
miTortugaMaria.forward(50)
miTortugaMaria.left(45)
